### ISSUE TITLE
betBTCTxLedger api call appears broken at bitpay

### ISSUE THREAD

**Issue by porkchop** [digitaltangibletrust/bitpay-api#1]
Try hitting it manually:

```
https://bitpay.com/api/ledger?c=BTC&startDate=2014-%C2%AD01%C2%AD-01&endDate=2014%C2%AD-05%C2%AD-31
```

The return array is always of length zero, which according to the docs is an error.

**Comment by taariq** [comment]
I would recommend opening up an issue with Bitpay on this if you think it's
important.

**Comment by porkchop** [comment]
Issue opened at bp. For reference: https://github.com/bitpay/nodejs-client/issues/4

**Comment by taariq** [comment]
LOL! CLOSING!

**Comment by karlkeefer** [comment]
@taariq I just started working on a fix for this.

**Comment by taariq** [comment]
@porkchop call mom! Karl's fucking around with the dead repos again!!!! MOOOOMMMM!!!

**Comment by porkchop** [comment]
@taariq Mom says it's time to PIVOT!! @karlkeefer we need this fix for our new direction asap! SPARTA!!!

**Comment by taariq** [comment]
![image](https://user-images.githubusercontent.com/701864/232903915-f1e761a0-13d6-4ec3-b1a0-f7650678e782.png)

**Comment by curtislacy** [comment]
Linked issue at bitpay is still open!  ONE of us has to deal with it, and they're clearly not going to!

**Comment by taariq** [comment]
OMG @curtislacy has entered the chat!
